### ISSUE TITLE
codeenvy ide java editor showing errors that are not errors

### ISSUE THREAD

**Issue by davidmoten** [codenvy/plugin-java#42]
See https://codenvy.com/ws/davidmoten/rtree
and open src/main/java/com/github/davidmoten/rtree/RTree.java using the CodeEnvy IDE.  The project builds without error using Maven build but the java editor indicates errors that are invalid.
 
![codenvy](https://cloud.githubusercontent.com/assets/318187/5055314/a101aa64-6cb5-11e4-9508-0e826b636c5a.png)

**Comment by skabashnyuk** [comment]
Do you experience the same issue today? Or it's no longer valid?
